- Cargo.toml
`cargo build` was failing with: 
```
error: failed to load source for a dependency on `curl`
Caused by:
Unable to update https://github.com/alexcrichton/curl-rust?branch=windows-separate-dir
Caused by:
failed to find branch `windows-separate-dir`
```
Checked out curl-rust and the fix was merged: https://github.com/alexcrichton/curl-rust/pull/175
> Remove [replace] of curl. Fix in windows-separate-dir merged into master branch of curl-rust.

- prost-derive/src/prost-derive.rs
- src/encoding.rs
- src/error.rs
- src/lib.rs
- src/message.rs
- test-all-types/src/lib.rs
Removes `io::Error` in favor of prost-specific error types.
`io::Error` is a bit heavyweight for prost, since there's no actual IO
done, and there are very few failure scenarios (only insufficient buffer
capacity when encoding, and malformed data when decoding). The new error
types can be converted to io::Error via a provided `From` impl.
CC @tarcieri
> Add prost-specific error types

- prost-build/Cargo.toml
That matches the version in prost-derive to not depend on two version of the itertools crate.
> Upgrade itertools to 0.7

- prost-build/src/lib.rs
The expected usage wasn't clear to me, it is likely it wouldn't be clear
for others.
#59.
> Enhance docs for the service generator

- README.md
- prost-build/src/code_generator.rs
- prost-build/src/ident.rs
- prost-build/src/lib.rs
- tests/src/build.rs
- tests/src/custom_attributes.proto
- tests/src/lib.rs
- tests/src/oneof_attributes.proto
This allows messages to be for example Serialize or Eq.
This is my attempt at what is suggested in #45. I hope the usage is clear from the documentation.
If you know of any attribute that can be placed on a field without bringing another dependency, I'll be happy to replace that slightly hacky comment test.
> Allow generation of attributes on messages and fields

- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
It can be used to output things that need to exist only once per file
(eg. a module). Contains empty default implementation, for cases when no
such thing is needed.
This is a solution for a real-life problem, the `tower-grpc` wants to put its traits into submodules (`client` and `service`), but this fails if there's more than one service in a proto file. See https://github.com/tower-rs/tower-grpc/pull/10.
> Add ServiceGenerator::finalize

- benchmarks/build.rs
- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
Changing ServiceGenerator::{generate, finalize} to take `&mut self` is
motivated by tower-rs/tower-grpc#21. The `ServiceGenerator` change
necessitated changing Config::compile_protos to take `&mut self` as
well. I don't expect the latter change to impact many people, since it's
the more advanced API (as opposed to the standalone `compile_protos`
function), and to be useful the API required a mutable config, anyway.
It also provides flexibility in the future if we want to do something
else requiring mutable access to the config.
This is a breaking change.
> prost-build: pass Config, ServiceGenerator by mut ref

- Cargo.toml
- conformance/Cargo.toml
- conformance/src/main.rs
- prost-build/Cargo.toml
- tests/Cargo.toml
Use env_logger 0.5 everywhere, instead of a mix of 0.5 and 0.4, to
avoid needing to download and build two versions. This won't have an
effect on standalone builds of prost because prost has a dev-dependency
on quickcheck, which uses env_logger 0.4 still. However, it will have
a positive effect on things that depend on prost-build and that use
env_logger 0.5.
Also, don't automatically enable the "regex" default feature of
env_logger. Things that depend on Prost can still enable it (and will
enable it by default, since it is a default feature) if they need it.
Contributed on behalf of Buoyant, Inc.
Signed-off-by: Brian Smith <brian@briansmith.org>
> Reduce env_logger-related dependencies.

- prost-build/src/lib.rs
It isn't useful to convert the environment variable to Unicode since
`Command` deals with `OsStr` (`Into<&OsStr>`) anyway.
Contributed on behalf of Buoyant, Inc.
Signed-off-by: Brian Smith <brian@briansmith.org>
>  Avoid unnecessary unicode conversion of OUT_DIR.

- prost-build/Cargo.toml
This drops the `ordermap` dependency, for example.
Contributed on behalf of Buoyant, Inc.
Signed-off-by: Brian Smith <brian@briansmith.org>
> Disable unneeded features of the petgraph library.

- prost-derive/Cargo.toml
Remove the indirect and unneeded dependency on failure_derive. In our
prost-based application, this change removes the following dependencies
from our Cargo.lock (partial output from `cargo update -p prost-derive`):
Removing failure_derive v0.1.1
Removing quote v0.3.15
Removing syn v0.11.11
Removing synom v0.11.3
Removing synstructure v0.6.1
Removing unicode-xid v0.0.4
Note in particular that prost itself is using a newer version of `syn` and
`quote` than `failure` is using.
Contributed on behalf of Buoyant, Inc.
Signed-off-by: Brian Smith <brian@briansmith.org>
> Remove unused failure_derive dependency.

- README.md
- prost-derive/src/field/map.rs
- prost-derive/src/field/message.rs
- prost-derive/src/field/mod.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
- tests/src/lib.rs
- tests/src/message_encoding.rs
This contains the tag inference logic extracted from #73.
> prost-derive: infer tag values of hand-written types

- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
- prost-build/src/message_graph.rs
- prost-types/src/protobuf.rs
This commit modifies prost-build to strip the enum name from enum
variants which include the enum name as a prefix. This style is common
with Protobuf (since it's heavily tied to C++ name resolution), however
it's non-idiomatic in Rust. To restore the previous behavior, a new
Config option is provided: `retain_enum_prefix`. This is a breaking
change.
> prost-build: strip enum name from enum variant prefix

- prost-build/Cargo.toml
- prost-build/build.rs
- prost-build/src/lib.rs
Now that the Protobuf include directory is bundled into the prost-build
crate, there's no reason not to fall-back to the `protoc` on the path
for host platforms which don't have a bundled `protoc`.
> prost-build: check PATH for protoc

- prost-build/src/code_generator.rs
- prost-types/src/protobuf.rs
fixes #86
This is a breaking change.
> codegen: derive Hash, Ord and PartialOrd for enums

- prost-derive/src/lib.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/no_unused_results.proto
- tests/src/no_unused_results.rs
This fixes danburkert/prost#101.
> Fix "warning: unused result" when using "#![warn(unused_results)]"

- prost-derive/Cargo.toml
- prost-derive/src/field/map.rs
- prost-derive/src/field/message.rs
- prost-derive/src/field/mod.rs
- prost-derive/src/field/oneof.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
Use patch number-sensitive version requirements because of the deprecated API present in `proc-macro2` 0.4.0..0.4.3 and both `quote` 0.6.0..0.6.2 and `syn` 0.14.0 use that API.
> Update dependencies for `prost-derive`

- src/encoding.rs
Fixes up functions deprecated by bytes crate 0.4.x.
> refactor: updates deprecated methods from bytes crate

- Cargo.toml
The get_*_be and get_*_le variants are not present in 0.4.6 and below.
> Update minimum version of bytes.

- prost-build/src/code_generator.rs
- tests/src/build.rs
- tests/src/default_enum_value.proto
- tests/src/lib.rs
Fix for #118 - If the `strip_enum_prefix` option is enabled, then default values for enum fields must have their prefixes stripped as well.
> Strip enum type prefix in default field values

- prost-build/src/code_generator.rs
- prost-types/src/protobuf.rs
To guarantee that their representation matches the assumed i32, allowing clients to safely transmute.
r? @danburkert
> Add `repr(i32)` to enums

- prost-build/src/code_generator.rs
- prost-types/src/compiler.rs
- prost-types/src/protobuf.rs
Specifically `Vec` and `String`.
Imagine you have a protobuf message type define like this:
```proto
message String {
option (a_private_extension_namespace.boxed_message).is_presence_box = true;
optional string value = 1;
}
```
Previously the Rust code generated by prost-build looks like this:
```rust
pub struct String {
#[prost(string, optional, tag="1")]
pub value: ::std::option::Option<String>,
}
```
The inner reference to `String` above should be referring to `std::string::String`,
but that is shadowed by the local definition of `String`. Fully-qualifying all `std`
types in codegen solves this.
Fixes https://github.com/danburkert/prost/issues/152
> Fully-qualify type names from `std` in codegen

- src/encoding.rs
> Fix UTF-8 unsoundness in string::merge

- Cargo.toml
- benches/benchmark.rs
- prost-derive/src/field/group.rs
- prost-derive/src/field/map.rs
- prost-derive/src/field/message.rs
- prost-derive/src/field/oneof.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
- src/encoding.rs
- src/lib.rs
- src/message.rs
- src/types.rs
- tests/src/groups.proto
- tests/src/lib.rs
- tests/src/nesting.proto
This PR implements a recursion limit, which can be disabled by not setting a Cargo feature (which is on by default). This change is technically not backwards compatible, but in practice very few programs should hit the recursion limit.
Although adding a context argument complicates the API somewhat, most clients would not implement or use the methods with the added argument and would instead only use `decode`, which is not changed.
Fixes #176 
r? @danburkert
> Implement a recursion limit

- Cargo.toml
This removes the byteorder-dependency, which does not seem to be referenced anywhere
> Remove byteorder-dependency

- prost-derive/src/field/group.rs
- prost-derive/src/field/map.rs
- prost-derive/src/field/message.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
They were inhibiting rustdoc from generating code for nested impl
blocks, and are no longer necessary since the new 2018 edition fully
qualified imports.
> prost-derive: remove unnecessary dummy consts

- prost-derive/Cargo.toml
- prost-derive/src/field/group.rs
- prost-derive/src/field/map.rs
- prost-derive/src/field/message.rs
- prost-derive/src/field/mod.rs
- prost-derive/src/field/oneof.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
This PR removes the `failure` dependency in `prost-derive` and replaces it with `anyhow`.  
The change is trivial, it is pretty much just a namespace change (eg. `s/failure::/anyhow::/g`).
**Closes #258.**
> Move from `failure` to `anyhow` in `prost-derive`

- src/encoding.rs
#194  introduced a ~3% regression on some decoding
benchmarks. My best guess is that swapping the value temporarily with a
new string is not being optimized well. This commit reverts to using
String::as_mut_vec, but carefully clears the string on decode failure.
It also fixes up the associated regression test, which wasn't properly
covering the malformed UTF-8 case.
// Before #194
dataset/google_message3_2/decode
time:   [219.45 ms 219.48 ms 219.51 ms]
thrpt:  [458.64 MiB/s 458.72 MiB/s 458.78 MiB/s]
// #194
dataset/google_message3_2/decode
time:   [226.08 ms 226.11 ms 226.18 ms]
thrpt:  [445.12 MiB/s 445.25 MiB/s 445.32 MiB/s]
// This commit
dataset/google_message3_2/decode
time:   [219.05 ms 219.76 ms 221.78 ms]
thrpt:  [453.94 MiB/s 458.12 MiB/s 459.61 MiB/s]
cc @mzabaluev @nrc
> Reintroduce unsafe in encoding::string::merge

- prost-derive/src/lib.rs
- src/encoding.rs
- src/types.rs
- tests/src/lib.rs
> apply recursion limit when skipping fields

- prost-build/src/code_generator.rs
- prost-types/src/protobuf.rs
- tests/src/build.rs
- tests/src/deprecated_field.proto
- tests/src/deprecated_field.rs
- tests/src/lib.rs
Protobufs support `deprecated` field options. These field options allow
the field to continue to be supported, but allow for language specific
code generators to include that the field has been deprecated in the
generated code. As discussed in https://github.com/danburkert/prost/issues/221 we should considersupporting this in `prost`.
This commit adds support for this feature in `prost-build` by checking
the field options, and if present emitting a `#[deprecated]` attribute.
One short coming of this change is that it is difficult to test that the
`deprecated` attribute is correctly added with an assertion since the
attribute is not accessible at runtime.
> Add support for `deprecated` attributes on fields.

- prost-build/src/ast.rs
- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
- protobuf/build.rs
- tests/src/default_enum_value.proto
- tests/src/unittest.rs
Fixes #310
Fixes an instances where setting a default field value to an enum variant with an 'untraditional' casing would cause a miscompile.
This is technically a breaking change, but it's unlikely that any affected programs would succeed to compile previously, so low impact.
> fix proto2 enumeration field default case transform

- .github/workflows/continuous-integration-workflow.yaml
It appears PR retries were failing due to (presumably)
https://github.com/actions/checkout/issues/23.
> CI: update to checkout@v2

- prost-types/Cargo.toml
- prost-types/src/lib.rs
I must have been under the impression that SystemTime couldn't handle
datetimes before the Unix epoch back when I wrote the conversion code in
2017. That is wrong, and so was the code.
BREAKING CHANGE: this is a breaking change to prost-types, because the
Timestamp TryFrom<SystemTime> impl is now the default impl, with a
different error type.
> fix Timestamp <-> SystemTime conversions

- prost-build/src/lib.rs
- tests/src/bootstrap.rs
This to allow setting `PROTOC=protoc`, which in turn allows for using a `protoc` found in `PATH`.
This is a breaking change.
> Remove the check for existing protoc at build time (#283)

- .github/workflows/continuous-integration-workflow.yaml
- prost-build/src/lib.rs
Fixes a prost-build compile failure when its built in isolation.
> prost-build: fix compilation error when using --no-default-features

- protobuf/Cargo.toml
Builds are failing on unrelated pull requests (e.g., #326) because the
`curl` crate has pushed a new version that depends on Rust 1.40, while
our CI tests against 1.39. We could probably bump to require 1.40 as
well, especially since we want to use the same `#[non_exhaustive]`
attribute, per #43. But a minimal change to unblock development and keep
the current minimum stable Rust version is to just pin `curl < 0.4.34`.
Test Plan:
Running `cargo +1.39.0 test --workspace --all-targets` passes on my
Linux machine.
wchargin-branch: deps-curl-pre-0.4.34
> deps: require `curl < 0.4.34` to fix MSRV

- Cargo.toml
- conformance/Cargo.toml
- prost-build/Cargo.toml
- prost-types/Cargo.toml
- protobuf/Cargo.toml
- src/encoding.rs
- tests-2015/Cargo.toml
- tests-no-std/Cargo.toml
- tests/Cargo.toml
This change updates the `bytes` crate dependencies to version 0.6.
Fixes https://github.com/danburkert/prost/issues/380
> Update bytes to 0.6

- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/proto3_presence.proto
Adds support for the new experimental
[proto3 optional primitive field][1] feature. Since this is an
experimental feature, it requires providing a flag to `protoc`, which is
enabled through a new `prost-build::Config::protoc_arg` API. To use the
new API, mark the primitive field `optional` as with proto2, and then
enable the experimental feature, see `protoc_arg` docs.
[1]: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md
> Add support for experimental proto3 optional field presence

- prost-build/src/extern_paths.rs
- tests/src/well_known_types.proto
- tests/src/well_known_types.rs
Checks that the well-known-type primitive wrappers retain optional-ness.
> Add well-known-type wrappers test

- .github/workflows/continuous-integration-workflow.yaml
This commit updates the use of seanmiddleditch/gha-setup-ninja in the CI pipeline to v3 from v1, which should remove the use of set-path, which was deprecated by GitHub.
This should allow builds to proceed in GitHub Actions.
> Update `seanmiddleditch/gha-setup-ninja` to v3

- prost-build/build.rs
Enable usage of bundled `protoc` when building for Mac on Apple Silicon (aarch64) by simply re-using the existing x86_64 OS X binary and have Rosetta seamlessly translate it.
One could later replace this with a natively compiled OS X aarch64 binary, but this was a quick easy solution and Rosetta is really quite efficient so likely is good enough for most.
Fix #393
> Add bundled support for Mac aarch64 through Rosetta

- prost-derive/src/field/mod.rs
- src/encoding.rs
1.50.0 introduced a new clippy lint that has one false positive that
this disables and one that was actually valid.  Given a refactor in that
file, prost_attrs was made into a private function.
Note that #436, or similar, is also needed to get CI green again.
> Fix clippy lints with 1.50.0

- protobuf/benches/dataset.rs
- protobuf/build.rs
- protobuf/src/lib.rs
Hi! It looks like the build's broken because the benchmarking test data at https://storage.googleapis.com/protobuf_opensource_benchmark_data/datasets.tar.gz isn't there anymore. 
I've [opened an issue with protobuf](https://github.com/protocolbuffers/protobuf/issues/8283) to see if it's been moved somewhere (that URL is still referenced in their repo too), but I figured in the meantime removing its usage from prost would be a good idea.
> Remove the downloading of big test data that's no longer available

- src/encoding.rs
I just noticed this while poking through the code. Fields of type `Bytes` can now be slices of a greater `Bytes` that is passed to Message::decode
The referenced issue https://github.com/tokio-rs/bytes/issues/374 was implemented as Buf::copy_to_bytes and `Bytes` features the zero-copy implementation https://docs.rs/bytes/1.0.1/src/bytes/bytes.rs.html#526-560
> Enable zero-copy support for bytes::Bytes fields

- README.md
- prost-build/src/lib.rs
This is mostly to fix #69 by documenting generated enum conversion functions in the README. 
I also wanted to make sure the generated code example was up to date, and it wasn't, so there's a commit for that. 
And while setting up a project to generate the code from the `tutorial` example, I hit a small hiccup in `prost-build`'s documentation, so there's a fix for that :)
Thank you! I'm happy to make any changes ❤️
> Documentation improvements

- src/error.rs
With the release of prost 0.7 `DecodeError::new` is marked as `pub(crate)`. This makes custom implementations of `Message` difficult to create. Since `DecodeError` is already used in a public trait (`Message`) it seems reasonable to be able to construct it externally
> Make DecodeError::new public

- benches/varint.rs
This gets rid of the warnings generated by the benchmark code.  This
does not completely replecate the old behavior, which created three
benchmarks, all with their own throughput, but given the same name.  I
don't think that same thing is possible anymore with the non-deprecated
APIs.
> Update from deprecated criterion::Benchmark to BenchmarkGroup

- prost-build/src/code_generator.rs
- tests/src/lib.rs
- tests/src/proto3_presence.proto
Optional scalar fields create a synthetic oneof, but we don't add those fields to the oneof_fields map since we just want to treat them as optional fields. However, if a message containing an optional scalar field also contained a real oneof, the code would enter the oneof processing logic and panic trying to load the fields of the synthetic oneof. We now just treat a lack of oneof fields as an indication that this oneof was synthetic and skip it.
Closes #430
> Fix messages with optionals and oneofs

- prost-build/src/lib.rs
- protobuf/build.rs
- tests/src/bootstrap.rs
This could be especially useful when one parameter (e.g. `protos`) is dynamically collected while the other (`includes`) is statically defined. Splitting the type should make `compile_protos` easier to use, I also changed a few instances where type conversion was used to show the impact.
> Remove path type generic for better ergonomic

- prost-types/src/lib.rs
- prost-types/src/protobuf.rs
- tests/src/well_known_types.rs
Implement `Hash` and an unstable/naive version of `Eq` for `Timestamp
A basic equality check on the internal fields of the `Timestamp`.
This implies that `normalized_ts != non_normalized_ts` even if `normalized_ts == non_normalized_ts.normalized()`.
This is acceptable to as timestamps across the network are already unstable.
The edge case is when the `Timestamp` is not normalized yet and would have mutated during the `normalize()` call.
> [prost-type] Impl `Hash + Eq` traits on `Timestamp`.

- prost-build/src/code_generator.rs
- tests/src/build.rs
- tests/src/default_string_escape.proto
- tests/src/lib.rs
The `default` is already unescaped.
> Fix escape for default string

- src/encoding.rs
* using `put_u8` simplifies the `encode_varint` code. this slightly changed behavior, but it should have no effect on prost. It improve performance while reducing unsafe code.
* inline `decode_varint` and remove some unnecessary unsafe.
bench
```
varint/small/encode     time:   [214.82 ns 214.91 ns 215.00 ns]
change: [-69.573% -69.350% -69.126%] (p = 0.00 < 0.05)
Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
4 (4.00%) low mild
3 (3.00%) high mild
8 (8.00%) high severe
varint/small/decode     time:   [231.53 ns 231.84 ns 232.21 ns]
change: [-17.817% -16.309% -14.947%] (p = 0.00 < 0.05)
Performance has improved.
Found 14 outliers among 100 measurements (14.00%)
6 (6.00%) high mild
8 (8.00%) high severe
varint/small/encoded_len
time:   [144.18 ns 144.37 ns …
```
> Improve encode_var/decode_varint performance

- prost-build/src/code_generator.rs
- prost-build/src/path.rs
Improves `PathMap`:
- Add iterator over all values matching a path (allow multiple attributes, with the same path and with sub-paths)  #490 #502
- Keep insertion order to avoid warnings/errors https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#legacy-derive-helpers
- Correctly handle field attributes on one-of #507
> Fix multiple attributes support

- src/encoding.rs
> Protect encoding::decode_varint from overflow

- prost-build/Cargo.toml
- prost-build/src/ast.rs
- prost-types/src/protobuf.rs
The PR fixes the problem of escaping URLs and Brackets in comments which fail on `clippy` lints.
Fixes #495
> Escape comments

- prost-build/Cargo.toml
- prost-build/src/ident.rs
There's a new version of `heck`. To prevent duplicate dependency
versions, this change updates `prost-build` to use `heck` v0.4
> Upgrade heck dependency to v0.4

- src/encoding.rs
See https://github.com/tokio-rs/prost/issues/571
The optimization in https://github.com/tokio-rs/prost/pull/449 avoids
copies when both the input and output are `Bytes`, but it can cause
double copies when neither the input nor output is `Bytes`.
This is easy to trigger by using `&[u8]` as the input buffer and merging
a `Vec<u8>` or `String`, both of which are generated by `prost-build`.
Introduce `encoding::bytes::merge_one_copy()` and use it to guarantee
that `encoding::string::merge()` copies exactly once. The new function
is only visible to the encoding module so it does not affect the API.
It would also be useful to make `prost-derive` call this for
`#[prost(bytes="vec")]`, but that may require making it public, which
is a more drastic and less justified change. It may be better to …
> prost: Avoid double-copy on merging string from non bytes

- prost-build/src/code_generator.rs
- prost-build/src/extern_paths.rs
- prost-build/src/lib.rs
- prost-build/src/path.rs
- prost-derive/src/field/scalar.rs
- src/encoding.rs
- tests/src/lib.rs
- tests/src/message_encoding.rs
- tests/src/unittest.rs
- tests/src/well_known_types.rs
Figured I'd start with recommendations in the current codebase as is, and that'll make handling https://github.com/tokio-rs/prost/issues/553 a bit easier.
> fix clippy linting recommendations (edition 2018)

- src/message.rs
`Message::encode_to_vec` and `Message::encode_length_delimited_to_vec`, introduced in https://github.com/tokio-rs/prost/pull/378, were previously only available with `std`-enabled builds.
I can't see any reason why they shouldn't be present with `no_std` builds. So this PR makes them available to `no_std` builds as well.
> enable encode_to_vec for no_std

- prost-build/src/code_generator.rs
- prost-build/src/path.rs
- prost-derive/src/field/map.rs
- tests/src/default_enum_value.proto
This handles clippy errors that showed up when switching over
to edition 2021. Note that we can't move to use edition 2021 until
the MSRV is set to 1.56. See https://github.com/tokio-rs/prost/issues/553 for
more details.
> fix edition 2021 clippy errors

- prost-build/Cargo.toml
This also adds the `unicode-bool` feature required by the `\s` regular expression character class. `unicode-bool` is a more minimal feature than `unicode-bool`. Without either of these features on the `regex` crate, testing `prost-build` will fail.
`regex` crate is updated to 1.5.5 due to [RUSTSEC-2022-0013](https://rustsec.org/advisories/RUSTSEC-2022-0013) security advisory on versions 1.5.4 and lower.
> chore: update regex dependency

- prost-build/src/lib.rs
- prost-build/src/message_graph.rs
This revives PR #313. With the advent of v1.0 of [buf.build](https://buf.build), the ecosystem for generating polyglot code from protobuf heavily favors the plugin model. It very easily slots into the `buf generate` model. This revival creates a distinct `protoc-gen-prost` crate to host the binary, rather than the prior method of putting the binary in the `prost-build` crate. This makes installation using `cargo install protoc-gen-prost` more convenient.
In my opinion, Prost would benefit from integrating into this model, so I wanted to revive the old protoc plugin. Even with this very basic PR (which doesn't handle options), I have confirmed that puting the binary onto the `PATH` and running `buf generate` results in precisely the Rust code I would expect over a somewhat complicated …
> Expose generation methods for buf

- prost-types/src/lib.rs
There are two broken hyperlinks ([first](https://docs.rs/prost-types/latest/prost_types/struct.Duration.html#method.normalize), [second](https://docs.rs/prost-types/latest/prost_types/struct.Timestamp.html#method.normalize)) in the documentation of the `normalize` functions for `Duration` and `Timestamp` in `prost-types` due to a missing empty line. This PR fixes them.
When rendered with `cargo doc`
Before: 
> Normalizes the timestamp to a canonical format.
> 
> Based on \[`google::protobuf::util::CreateNormalized`\]\[1\]. \[1\]: https://github.com/google/protobuf/blob/v3.3.2/src/google/protobuf/util/time_util.cc#L59-L77
After:
> Normalizes the timestamp to a canonical format.
>
> Based on [google::protobuf::util::CreateNormalized][1] 
>
> [1]: …
> Fix hyperlinks in doc

- prost-build/src/lib.rs
This allows a consumer to use `Module` as the key in a `BTreeMap` in addition to a `HashMap`.
> feat: implement Ord and PartialOrd for Module

- Cargo.toml
- README.md
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- src/lib.rs
Release 0.10 brings a few new ....
- `protoc` is no longer bundled but is now compiled from bundled source
- Minor performance improvements
- Methods exposed to allow third party protobuf generation libraries
> Prepare 0.10 release

- prost-types/src/datetime.rs
- prost-types/src/lib.rs
This PR implements to and from string methods for
`prost_types::Timestamp` following the RFC-3339 timestamp format, as
also specified by the [Protobuf JSON mapping spec][1]. The `Display`
impl always emits the Zulu (Z) timezone, whereas the parser is slightly
lenient in accepting fixed timezone offsets, as well as both the `T` and
space seperated date and time portions. This leniency in parsing makes
it much much more robust to parsing data of less-than-pristine
formatting, even though the protobuf spec allows no leniency.
Also, since it was easy with the new date time functionality, we've gone
ahead and added a trio of convenience construct functions to `Timestamp`
which makes it straightforward to create `Timestamp`s out of calendar
date time information.
This functionality will be used …
> impl Timestamp::{Display, FromStr} with RFC-3339 format

- prost-types/src/datetime.rs
- prost-types/src/lib.rs
This PR implements to and from string methods for
`prost_types::Duration` following the duration format defined by the
[Protobuf JSON mapping spec][1].
This is a followup to #615 and re-uses a lot of the same parser helpers.
Additionally I did the same error type unification with a new
`DurationError` type. This is a breaking change for `prost-types` since
public APIs are changed slightly.
[1]: https://developers.google.com/protocol-buffers/docs/proto3#json
> impl Duration::{Display, FromStr} with protobuf format

- prost-build/src/lib.rs
The variable should be named `PROTOC_NO_VENDOR` but has a typo in the prost-build lib documentation.
> docs: Fix typo in PROTOC_NO_VENDOR environment variable doc

- prost-build/src/lib.rs
- tests/src/build.rs
- tests/src/well_known_types.rs
This reverts commit c577d3f.
Fixes https://github.com/hyperium/tonic/issues/964
> Revert "build: Skip empty protobuf files (#605)"

- prost-derive/src/lib.rs
> prost-derive: document methods generated by `prost::Oneof`

- .github/workflows/continuous-integration-workflow.yaml
- prost-build/Cargo.toml
- prost-build/src/ast.rs
- prost-build/src/lib.rs
- prost-types/src/compiler.rs
- prost-types/src/protobuf.rs
- tests/Cargo.toml
I have been working with protocol buffers whose documentation includes code blocks, often things like example service descriptions and the like (consider https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L67-L81 )
As such, it's important that by the time prost-build has run, the code blocks in those comments have been transformed into something safe from `rustdoc`'s test extractor.
This PR is split into three commits.  The first adds the code-block processing support.  The second fixes up ensuring there's leading spaces in the comments to retain the pleasant-ish human look, and the third updates the generated code files for `prost-types` so that things are consistent.
> Correct codeblocks to not break `cargo test --doc`

- prost-build/src/code_generator.rs
- prost-types/src/compiler.rs
- prost-types/src/protobuf.rs
- tests/src/lib.rs
To be more convention compliant.
> Replace `.to_str_name()` with `.as_str_name()`

- .github/workflows/continuous-integration-workflow.yaml
Older versions use node 12 which is no longer supported (end-of-life on April 30, 2022).
> Update actions/checkout action to v3

- prost-types/src/lib.rs
Fixes #682 by allowing i64 wrapping during negation. 
This allows `seconds = i64::MIN` to pass with debug checks enabled.
> Permit overflow with wrapping.

- Cargo.toml
Looks like since I've last looked at the repo the update to
[MSRV 1.56 happened](https://github.com/tokio-rs/prost/pull/669) and we don't have any clippy errors on the 2021
edition. Therefore, I _think_ we can just up the edition now. 
If there's a good reason not to do so let me know and I can close this. 
I've also set the MSRV explicitly in the Cargo.toml so that users that happen to have an older rust version set (like I did when I was testing 1.51 at some point) get an error telling them they're on the wrong version instead of abstruse compiler errors. 
Closes #553, also closes #595 since 1.51 will no longer be supported.
> Move edition to 2021

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
_PROST!_ is a [Protocol Buffers](https://developers.google.com/protocol-buffers/) implementation for the
[Rust Language](https://www.rust-lang.org/). `prost` generates simple, idiomatic Rust code from `proto2` and
`proto3` files.
Relase 0.11 brings a few breaking changes and changes to how prost
sources protoc.
- `prost-build` now requires `protoc` to be available in the path or set
via the `PROTOC` env var.
- `prost-types` now contains new `Timestamp`/`Duration` `FromStr` implementations.
- MSRV bump to `1.56` and all crates have been moved to edition 2021
Notible changes that are not breaking:
- `prost-build` now has a `cleanup-markdown` feature for cleaining up
code blocks from protobuf files so that they work under rustdoc tests.
- `prost-build` now generates `as_str_name` for message …
> chore: Prepare 0.11 release

- prost-build/src/ast.rs
- prost-types/src/protobuf.rs
In v0.11.0 the `sanitize_line` function was updated to add a space to
the beginning of non-empty RustDoc comments, but often those comments
already contain a space. This commit updates the check to ensure the
extra space is only added if it doesn't already exist.
Fixes #693.
> Don't add extra space before RustDoc comments

- prost-build/README.md
This is no longer supported as of v0.11. See ac57645 for its removal.
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> Remove notes from prost-build about building protoc

- prost-build/src/ast.rs
I'm trying to make prost_build run several generators, because I want to make http and grpc servers. So I've written this code, but it fails to compile because `Service` doesn't implement `Clone`, so I've added the derive.
```rust
//<...>
impl ServiceGenerator for GeneratorList {
fn generate(&mut self, service: Service, buf: &mut String) {
for gen in self.generators.iter_mut() {
gen.generate(service.clone(), buf); // Error: clone not found
}
}
// <...>
}
```
> add clone to Service type

- prost-build/src/lib.rs
Modify the example code for prost-build so that it uses the right module structure.
Otherwise this might cause issues if the proto imports other protos.
-----
However, it would be better if the example used directly the Config::include_file method, to make it easier to discover :). I can also change that if needed.
> Add snazzy module to example

- prost-build/src/fixtures/imports_empty/_expected_include.rs
- prost-build/src/fixtures/imports_empty/imports_empty.proto
- prost-build/src/lib.rs
References:
Original report: https://github.com/tokio-rs/prost/issues/228
My report: https://github.com/tokio-rs/prost/issues/724
Partial fix in: https://github.com/tokio-rs/prost/pull/605
Issue with fix: https://github.com/hyperium/tonic/issues/964
Reverted in: https://github.com/tokio-rs/prost/pull/639
After digging in, the issue with the first fix is that while it prevented the file from being generated, it did not prevent the file from being referenced in the "include" file because both locations iterate the module hash. My proposed solution is to instead avoid adding the empty module to the list at all. Then the file does not get output and the include file does not have an entry that would otherwise be referencing an empty file.
Also did a small refactor pass on the surrounding loop …
> Ignore empty codegen modules in outputs

- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
I have a use case where I'm building a wrapper around `prost-build` in combination with `prost-reflect` to extract protobuf custom options and do some magic.
However, since this wrapper, let's call it `my-build`, will be used from a large number of different crates it would be ideal to have the `my-core` crate re-export `prost` to simplify upgrades down the line.
In order to facilitate this use case I've added a simple configuration option which would allow me to change the default `#[derive(::prost::Message)]` to `#[derive(::my_crate::prost::Message)]`.
Hopefully, it's a simple enough change that it won't be too controversial 😄 
Please let me know if there's anything you'd like me to change.
> Allow generated `Message` derive path to be changed

- prost-build/src/code_generator.rs
This follows up on #729 and adds a few more places where we replace the prost_path.
> feat(build): Allow changing prost crate path

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
- build: Improve `protoc` sourcing instructions in error messages.
- build: Add `Clone` to `Service` types.
- build: Sort modules to produce deterministic include files.
- core: Tuple struct support.
- build: Allow generated code derive path's to be changed.
- build: Allow changing prost crate path.
- build: Add code formatting support.
> chore: Prepare `0.11.2` release

- prost-build/src/lib.rs
As far as I can tell `protobuf3-compiler` doesn't actually exist in `apt`.
> Fix debian hint

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where prost already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
> CI: add CIFuzz github action

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- src/lib.rs
- build: Use `log` to print error logs.
- build: Remove accidentally included prints.
- build: Improve debian error message hint.
> chore: Prepare 0.11.3 release

- README.md
Fixes proto code block highlight on GitHub.
> chore(doc): Fix proto code block

- conformance/src/main.rs
- prost-build/src/lib.rs
- prost-derive/src/field/map.rs
- prost-types/src/datetime.rs
- prost-types/src/lib.rs
- protobuf/build.rs
- src/encoding.rs
- tests/src/bootstrap.rs
- tests/src/build.rs
- tests/src/debug.rs
- tests/src/message_encoding.rs
> chore: Fix clippy lint

- prost-build/src/ast.rs
- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
The file descriptor sets generated by rules_proto in bazel don't have this by default, so this allows some flexibility for users to reuse results that are already available to them.  It's fairly trivial adjustment so it seemed reasonable to me to allow the flexibility.
> Allow file descriptor be generated without --include_source_info

- prost-build/src/code_generator.rs
- prost-build/src/fixtures/helloworld/_expected_helloworld.rs
- prost-build/src/fixtures/helloworld/types.proto
- prost-build/src/lib.rs
> Add message and enum attributes to prost-build

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
- build: Add message and enum attributes (https://github.com/tokio-rs/prost/pull/784)
> chore: Prepare `0.11.6` release

- .github/workflows/continuous-integration-workflow.yaml
This PR adds Kani to the CI as previously discussed with @LucioFranco.
- This PR adds Kani verification to only the `tests::check_timestamp_roundtrip_via_system_time` proptest harness. We focused on this harness because it was involved in bug #682
- Remaining harnesses within `prost-types` are blocked by [Kani issue 274](https://github.com/model-checking/kani/issues/274). We are working to implement the required features to resolve 274 and we will submit a second PR to enable these harnesses once Kani implements the feature.
- Harnesses outside of `prost-types` will be difficult to support within GitHub Actions due to Kani's large memory consumption when running these harnesses.
> Add Kani to CI.

- prost-types/src/lib.rs
If `seconds` are `0`, but `nanos` are negative, `Duration::try_from` incorrectly treats the duration as positive.  The negative `nanos` are unconditionally cast to `u32`, leading to an invalid positive `Duration`.  
1. Fixes the check.
2. Adds a regression test for the reproducer.
3. Adds a proptest to detect any cases where this might occur.
This issue was found using [Kani Rust Verifier](https://github.com/model-checking/kani)
> Fix issue with negative nanos in Duration::try_from(), and add tests

- prost-types/src/lib.rs
The `check_duration_roundtrip` proptest can suffer a spurious overflow in the case where `seconds` is `u64::max` and `nanos > 1_000_000_000`.  This was blocking Kani verification of the harness.  Update to limit nanos to the legal range.
> Prevent spurious overflow in check_duration_roundtrip test

- prost-build/src/lib.rs
Added a line clarifying that `default_package_filename` receives a base-name and adds an extension itself.
Issue:
- https://github.com/tokio-rs/prost/issues/807
> Clarify `default_package_filename` documentation.

- prost-types/src/lib.rs
Removes including generated codes from prost-types. This wil improve our development experience allowing rust-analyzer to jump to the actual generated codes instead of the include sentence.
> chore(types): Remove including generated code

- .github/workflows/continuous-integration-workflow.yaml
Updates github action configs.
- Switches to dtolnay/rust-toolchain from actions-rs/toolchain as it is outdated.
- Switches to use `run:` from actions-rs/cargo as it is outdated.
- Switches to baptiste0928/cargo-install from actions-rs/cargo when install a tool.
- Update Swatinem/rust-cache to v2 from v1.
> chore: Update github action

- .github/workflows/continuous-integration-workflow.yaml
- conformance/Cargo.toml
- prost-types/Cargo.toml
- protobuf/Cargo.toml
Adds cargo-machete to detect unused dependencies in order to keep manifests not to depend on unused crates, and removes detected crates.
> chore: Add cargo-machete to detect unused dependencies

- Cargo.toml
- prost-build/Cargo.toml
- prost-derive/Cargo.toml
- prost-types/Cargo.toml
Updates rust-version field in manifests to follow to #814.
> chore: Update msrv to 1.60

- prost-types/src/lib.rs
Hi!
I'm using `Timestamp` in a context where the overflow handling in `normalize` isn't really ideal (I'm transforming a `Timestamp` to a `chrono::DateTime<Utc>`, which needs unsigned nanos, and I am better off dropping the timestamp than recording faked values), and I implemented this in my project and though it might be handy to upstream. Let me know what you think!
Thanks,
Olly
> Added try_normalize to Timestamp

- KANI.md
You need to do a submodule init in order for PropProof to work.  Add this fact to the docs.
> Update PropProof docs to note the need to submodule init

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
MSRV for prost has been updated to 1.60.
- types: Fix issue with negative nanos in Duration::try_from(), and add tests [#803](https://github.com/tokio-rs/prost/pull/803)
- build: Clarify default_package_filename documentation. [#809](https://github.com/tokio-rs/prost/pull/809)
- types: Added try_normalize to Timestamp [#796](https://github.com/tokio-rs/prost/pull/796)
- build: Add direct fds compile support [#819](https://github.com/tokio-rs/prost/pull/819)
> chore: Prepare `0.11.7` release

- prost-types/src/lib.rs
Introduced in #801
Closes #823
> fix: correct change in visibility of compiler module

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
- types: Fix unintentional change in compiler module visibility [#824](https://github.com/tokio-rs/prost/pull/824)
`prost-types` 0.11.7 was yanked due to the above unintentional semver breakage.
> chore: Prepare `0.11.8` release

- .github/workflows/continuous-integration-workflow.yaml
- KANI.md
* Adds the `check_duration_roundtrip_nanos` test to the harnesses run with Kani in CI
* Avoid recursive submodule initialization for `propproof` because it isn't needed (see https://github.com/model-checking/kani-github-action/pull/24)
* Upgrade Kani's GitHub Action to use version `0.23`
Note: This PR doesn't change the test, it was added in #803
> Add existing roundtrip test to Kani CI and avoid recursive submoduling

- prost-build/Cargo.toml
They both have the same MSRV: 1.56.0
https://github.com/dtolnay/syn/blob/master/Cargo.toml#L21
https://github.com/dtolnay/prettyplease/blob/master/Cargo.toml#L15
> Update to `syn@2` & `prettyplease@0.2`

- tests/single-include/Cargo.toml
This library will fail to build with the following error when checked out into a directory not named exactly `prost`:
```
error: failed to load manifest for workspace member `/home/alex/src/prost-rs/tests/single-include`
Caused by:
failed to load manifest for dependency `prost`
Caused by:
failed to read `/home/alex/src/prost/Cargo.toml`
Caused by:
No such file or directory (os error 2)
```
This is because the `single-include` test depends on `prost` with the path `../../../prost`. This patch fixes the issue by correcting the path to `../..`.
> Fix build in directory not named `prost`

- prost-build/src/code_generator.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes_formatted.rs
- prost-build/src/fixtures/field_attributes/field_attributes.proto
- prost-build/src/lib.rs
This allows the user to request boxing of specific fields. This is useful for enum types that might have variants of very different size.
If the large variants are infrequent, then that means we reduce the size of messages, which makes them use less memory, and requires less CPU time when moving them.
In Buck2, we encode our logs as protobuf, this commit shows the wins of using boxing:
https://github.com/facebook/buck2/commit/afb3307b6141d87b88f1de9f7f74bd9791ad2293
> prost-build: support boxing fields

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
- build: Support boxing fields via `Config::boxed` ([#802](https://github.com/tokio-rs/prost/pull/802))
> chore: Prepare `0.11.9`

- prost-build/Cargo.toml
- prost-build/src/ast.rs
Replaces `lazy_static` with `once_cell` as `lazy_static` will go to deprecated officially and `once_cell` will go to the standard library.
> chore(build): Replace lazy_static with once_cell

- prost-derive/src/field/scalar.rs
The `Message` derive macro currently generates `Debug` implementations that contain code that violates the `non_snake_case` linter rule[^1]. This PR changes the macro expansion to add an `#[allow(...)]` attribute for this rule.
**Note**: If there is consensus that the solution is OK, I'll fix any failing tests to make this PR ready to merge.
[^1]: https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/nonstandard_style/static.NON_SNAKE_CASE.html
> Fix `non_snake_case` warning on generated identity functions

- README.md
- prost-derive/src/field/map.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
- tests/src/lib.rs
Related to #812.
This allows us to more easily have generic functions that deal with conversions between i32 and prost Enums.
I took the liberty of deprecating `from_i32` and updating the README.md to show how to use the TryFrom<i32> instead of `from_i32`. I also changed code that used `from_i32` so that it uses `try_from`. If this is not how things are usually done in this repo, please tell me so I can undo those changes and make it so the only change is the addition of the TryFrom<i32> implementation and the new test.
Also, one point that I am not sure about is the Error type of the TryFrom<i32> implementation. I used DecodeError, but if that is not suitable and I should create a new Error struct/enum, please tell me so I can fix it.
> feat: add TryFrom<i32> implementation to Enumeration

- prost-build/Cargo.toml
- prost-build/src/ast.rs
- prost-types/src/protobuf.rs
A proposal to fix https://github.com/tokio-rs/prost/issues/850.
Allows linking to items in doc comments by not escaping brackets followed by parenthesis.
- Before (brackets always escaped):
`// Some comment with a [Link]` -> `/// Some comment with a \[Link\]`
`// Some comment with a [Link](Link)` -> `/// Some comment with a \[Link\](Link)`
- After (brackets not escaped if followed by parenthesis):
`// Some comment with a [Link]` -> `/// Some comment with a \[Link\]`
`// Some comment with a [Link](Link)` -> `/// Some comment with a [Link](Link)`
EDIT: I also implemented the case with brackets following brackets `[Link][Link]` since it appears in some of the tests.
EDIT: I also implemented not escaping brackets which are already escaped, it happens when using the `cleanup-markdown` feature, …
> prost-build: do not escape brackets followed by parenthesis in comments

- README.md
The upstream change https://github.com/protocolbuffers/protobuf/commit/3c3dfe0efa859563e1fdbe51badd0ebf74760ff9 broke the anchor link
This corrects the link
> fix protoc install link

- .github/workflows/ci.yml
- prost-types/src/lib.rs
- src/lib.rs
- src/name.rs
As discussed in #299 and #858, adds a `Name` trait which associates a type name and package constants with a `Message` type. It also provides `full_name` and `type_url` methods.
The `type_url` method is used by newly added methods on the `Any` type which can be used for decoding/encoding messages:
- `Any::from_msg`: encodes a given `Message`, returning `Any`.
- `Any::to_msg`: decodes `Any::value` as the given `Message`, first validating the message type has the expected type URL.
> feat: `Name` trait + `Any` encoding support

- Cargo.toml
- README.md
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
- Bump `syn`  to version 2
- Bump MSRV to 1.64
- Added `TryFrom<i32>` for enums
- Optional debug implementations
- Initial generic `Any` and `Name` impl/traits.
> chore: Prepare `v0.12.0` release

- prost-types/src/lib.rs
👋 
Our proxy, which checks if we are not making the same RPC with the same payload at the same time, requires the implementation of a hash.
> prost-type: impl Hash for Duration

- flake.nix
- prost-derive/src/field/map.rs
- prost-derive/src/field/scalar.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/mod.rs
- tests/src/option_enum.proto
- tests/src/option_struct.proto
- tests/src/result_enum.proto
- tests/src/result_struct.proto
Same as PR #916 plus one commit that contains a unit test that covers the case  where `Option` was used instead of `::core::option::Option`.
PR #916  description: 
this pull request contains 3 commits:
1. [add cmake and ninja in the flake](https://github.com/tokio-rs/prost/commit/7b15ffd0d1774f78244e3a35068f657f09723331): Was needed to run cargo test from the test directory
2. [unit-test added to replicate issue](https://github.com/tokio-rs/prost/commit/30c800d03f75e376293a49e1271760d8985ff418): Replicates the error described in issue #905 
3. [fix: Use full path of Result type](https://github.com/tokio-rs/prost/commit/16e7e35865a16cfa8dc877c1986d0bffda0944eb): Fixes issue
https://github.com/tokio-rs/prost/issues/905
> Fixes 905, fix: Use full path of Result type + unit test + Option unti test

- src/name.rs
`full_name()` seems to generate the full name in the wrong order (given the examples in the doc comments, `TypeName.google.protobuf` instead of `google.protobuf.TypeName`).
> fix: generate `Name::full_name` properly

- .github/workflows/ci.yml
- prost-build/src/code_generator.rs
- prost-build/src/lib.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/type_names.proto
- tests/src/type_names.rs
Adds an option to implement the `Name` trait (added in #896) for message types.
Domains names for type URLs can be set with `type_name_domains`.
It's possible that this doesn't have to be a `PathMap`, but a single value for the entire config. Or something completely different.
Resolves #926.
> feat: Generate implementation for `Name` trait

- Cargo.toml
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- src/lib.rs
Hi there! This prepares release `0.12.2` which notably includes #931.
Note - I think setting `html_root_url` is deprecated (see https://github.com/rust-lang/api-guidelines/issues/229). I can remove it altogether if you're okay with it.
> prost: prepare release `0.12.2`

- prost-build/src/code_generator.rs
- src/name.rs
- tests/src/type_names.proto
- tests/src/type_names.rs
Fixes a bug in #931.
In code generator, `package` field was used to track nesting of messages and didn't represented the protobuf's "package" name. Nested names are now contained in `type_path` and `package` refers to file's package.
> Fix code generation for Name trait

- Cargo.toml
- prost-build/Cargo.toml
- prost-derive/Cargo.toml
- prost-types/Cargo.toml
Prepare release `0.12.3` to include the fixes in #944. I think we should probably yank `0.12.2` right?
> prost: prepare release `0.12.3`

- prost-build/src/code_generator.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/submessage_without_package.proto
- tests/src/submessage_without_package.rs
When package name is empty, but type_path is filled, the fq_message_name should begin with a single dot.
Two duplicate implementations are moved to a separate function.
A test is added that creates a sub message without a package name. The code generator uses the message name to generate a rust module path, which is invalid.
fixes: #843
> fix: fq_message_name should begin with one dot

- Cargo.toml
- prost-build/Cargo.toml
Adds `dep:` prefix to feature dependencies.
> chore: Add dep: prefix to feature dependencies

- prost-build/Cargo.toml
- prost-build/src/lib.rs
Rather than trying to predict if the OS will be able to find the binary before executing it we can just execute the binary and let the OS tell us if it found it or not.
This is IMO more correct and lets us remove a dependency that required a rust version far above the projects MSRV.
> Remove which dependency

- .github/workflows/ci.yml
Updates to `actions/checkout@v4` from version 3.
> chore: Update to actions/checkout@v4

- .github/workflows/ci.yml
`taiki-e/install-action` supports `cargo-machete` at [2.16.0](https://github.com/taiki-e/install-action/blob/v2.16.0/CHANGELOG.md#2160---2023-08-19). This action downloads the binary release.
> chore: Use taiki-e/install-action to setup cargo-machete

- .devcontainer/devcontainer.json
Add configuration to dev container [1] to ease development for new contributors. Github Codespaces will automatically load the correct environment to start development. VSCode will suggest to re-open the project in a dev container.
[1]: https://containers.dev/
> build: Add development container config

- src/encoding.rs
I believe this is probably allowing the compiler to unroll the loop where it could not before by giving it a more easily provable bound. This has significant performance improvement for me in benchmarks (on two different processors: a 7-series AMD and an old intel mobile processor; break-even on 3-series threadripper); if we have a process for validating these on more machines we should go through it and get more info.
> improve encode_varint performance by bounding its loop

- prost-build/src/lib.rs
- fixes missing whitespace between the error message and the OS-specific hint
- more succinct wording in error message
- capitalization ("debian" -> "Debian")
- consistent grammar tenses, slightly more formal and direct tone
- `os_specific_hint` now has hard breaks at 80 chars (just like `error_msg`)
Before:
```
--- stderr
thread 'main' panicked at /home/allan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.12.1/src/lib.rs:1475:10:
Could not find `protoc` installation and this build crate cannot proceed without
this knowledge. If `protoc` is installed and this crate had trouble finding
it, you can set the `PROTOC` environment variable with the specific path to your
installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from …
```
> fix: Improve protoc not found error message

- Cargo.toml
- src/lib.rs
- tests-no-std/Cargo.toml
> feat: add derive feature

- prost-build/Cargo.toml
- prost-derive/Cargo.toml
0.12 didn't change the syntax of any APIs in-use.
Additionally, the tests do pass with 0.12.
> Allow itertools 0.12

- prost-build/Cargo.toml
heck 0.5 didn't change the syntax of any APIs in-use.
> build(deps): Allow heck 0.5

- prost-build/Cargo.toml
multimap 0.10 didn't change the syntax of any APIs in-use.
> build(deps): Allow multimap 0.10

- README.md
- prost-build/src/lib.rs
- prost-types/src/lib.rs
Open question:
- What is the function of `prost-derive` feature?
> docs: Document feature flags

- Cargo.toml
- prost-build/Cargo.toml
- prost-derive/Cargo.toml
- prost-types/Cargo.toml
This patch update brings new features and fixes:
- Bump MSRV to 1.70 (minimum supported Rust version)
- Rename cargo feature `prost-derive` to `derive` (#992)
- Add @generated comment on top of generated files (#935)
- Optimize implementation of prost::Name when generated by prost-build (#956)
- build(deps): Allow itertools 0.12 (#948)
- build(deps): Allow heck 0.5 (#1012)
- build(deps): Allow multimap 0.10 (#1013)
- Improve protoc not found error message (#937)
- build: Add development container config (#949)
- docs: Fixed README typos (#952 / #967 / #970)
- …
> chore: Release version 0.12.4

- prost-build/src/code_generator.rs
Use the helper function to replace repetitive expressions obtaining prost library path from the configuration with fallback to "::prost".
> prost-build: `prost_path` helper function

- .github/workflows/ci.yml
- conformance/src/main.rs
- prost-build/src/code_generator.rs
- prost-build/src/ident.rs
- prost-derive/src/field/mod.rs
- prost-derive/src/field/scalar.rs
- prost-derive/src/lib.rs
- prost-types/src/any.rs
- prost-types/src/datetime.rs
- prost-types/src/timestamp.rs
- src/encoding.rs
- src/error.rs
- src/message.rs
- src/name.rs
- src/types.rs
- tests/src/build.rs
- tests/src/debug.rs
- tests/src/deprecated_field.rs
- tests/src/lib.rs
- tests/src/message_encoding.rs
- tests/src/skip_debug.rs
> Fix clippy warnings and enable clippy in CI

- .github/workflows/ci.yml
- .gitmodules
- protobuf/Cargo.toml
- protobuf/build.rs
Instead of downloading a tarball, use a submodule to get the protobuf sources. Newer versions of protobuf require recursive submodules for its dependencies
In preparation of updating the protobuf version used for conformance tests.
> build: Use git submodule to download protobuf sources

- .github/workflows/ci.yml
- protobuf/build.rs
- chore: Fix needless borrow
- ci: Clippy requires checking out submodules
- ci: Exclude `protobuf` project from clippy
> chore: Fix clippy checks in CI

- prost-build/src/code_generator.rs
- prost-build/src/code_generator/c_escaping.rs
Part of a series of module splits which became clear from https://github.com/tokio-rs/prost/pull/1026. Also functions as a way to improve the final reviewability of #1026.
> chore - codegen: extract c string escaping to a separate file

- prost-build/src/code_generator.rs
- prost-build/src/collections.rs
- prost-build/src/lib.rs
Part of a series of module splits which became clear from #1026. Also functions as a way to improve the final reviewability of #1026.
~~Depends on #1020~~(rebased)
> prost_build: `BytesType and MapType` into a `collections` module.

- conformance/Cargo.toml
- fuzz/Cargo.toml
- fuzz/afl/proto3/Cargo.toml
- protobuf/Cargo.toml
- tests-2018/Cargo.toml
- tests-no-std/Cargo.toml
- tests/single-include/Cargo.toml
The published crates were already using edition 2021. Update all internal crates as well.
Also add a new tests-2018 crate that runs all tests using edition 2018.
> chore: Update internal crates to Rust edition 2021

- prost-build/Cargo.toml
- prost-build/src/config.rs
Fixes: #1021 
~~Depends upon: #1020.~~
> Place `Config::format` behind the `format` feature flag.

- prost-build/src/code_generator.rs
- prost-build/src/code_generator/syntax.rs
Part of a series of module splits which became clear from #1026. Also functions as a way to improve the final reviewability of #1026.
> chore - codegen: `Syntax` to a separate file

- prost-build/src/code_generator.rs
When massaging field data in `CodeGenerator::append_message`, move it into lists of `Field` and `OneofField` structs so that later generation passes can operate on the data with less code duplication.
Subsidiary `append_*` methods are changed to take references to these structs rather than moved data, as generation of lexical tokens does not actually consume any owned data, and we will need more passes over the same field lists for the upcoming builder codegen in #901.
> style(prost-build): Consolidate field data into struct

- .github/workflows/ci.yml
- fuzz/Cargo.toml
- prost/Cargo.toml
- tests-2015/Cargo.toml
- tests-no-std/Cargo.toml
- tests/Cargo.toml
- tests/src/lib.rs
Found these unused dependencies using: `cargo +nightly udeps && cargo +nightly udeps --all-targets`
> tests: Remove unused dependencies

- README.md
the badge image has been incorrect and not reflective of CI status since august 2023 (9c877ce32ec0c465e437144c1bf4a27cb3aa705c).
> fix the link and badge for CI

- prost-build/src/code_generator.rs
A helper method to capture the logic of deciding whether a field needs to be boxed. This follows the pattern with other methods like `optional`, and will allow reusing the logic in the upcoming builder codegen in #901.
> prost-build: `CodeGenerator::boxed` method

- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- prost/Cargo.toml
- prost/src/lib.rs
This patch update brings new fixes:
- fix: include_file should handle proto without package (#1002)
- Place Config::format behind the format feature flag
- Handle keyword `Self` after stripping enum type prefix (#998)
- fix(readme): fix the link and badge for CI (#1049)
- style(codegen): `Syntax` to a separate file (#1029)
- chore(codegen): extract c string escaping to a separate file (#1028)
- style(prost-build): `CodeGenerator::boxed` method (#1019)
- style(prost-build): Consolidate field data into struct (#1017)
- style(prost-build): `BytesType and MapType` …
> chore: Release version 0.12.5

- prost-build/src/lib.rs
fixes: #1062
I'm adding this to fix a breaking change introduced in https://github.com/tokio-rs/prost/pull/1020 where these items were moved.
Since `0.12.5` this is causing build failures after `cargo update`.
```
Compiling grpc-build v6.1.0
error[E0432]: unresolved imports `prost_build::protoc_from_env`, `prost_build::protoc_include_from_env`
--> /Users/ethan.brierley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/grpc-build-6.1.0/src/lib.rs:3:19
|
3 | use prost_build::{protoc_from_env, protoc_include_from_env, Module};
|                   ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^ no `protoc_include_from_env` in the root
|                   |
|                   no `protoc_from_env` in the root
```
> fix(prost-build): re-export `error_message_protoc_not_found`, `protoc_from_env` & `protoc_include_from_env`

- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/Cargo.toml
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- prost/Cargo.toml
- prost/src/lib.rs
This patch update fixes a regression:
- fix(prost-build): re-export `error_message_protoc_not_found`, `protoc_from_env` & `protoc_include_from_env` (#1063)
> chore: Release version 0.12.6

- prost-build/src/code_generator.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes_formatted.rs
- prost-build/src/message_graph.rs
- prost-types/src/datetime.rs
- prost-types/src/duration.rs
- prost-types/src/protobuf.rs
- prost-types/src/timestamp.rs
- tests/src/build.rs
- tests/src/derive_copy.proto
- tests/src/derive_copy.rs
- tests/src/lib.rs
Rust primitive types can be copied by simply copying the bits. Rust structs can also have this property by deriving the Copy trait.
Automatically derive Copy for:
- messages that only have fields with primitive types
- the Rust enum for one-of fields
- messages whose field type are messages that also implement Copy
Generated code for Protobuf enums already derives Copy.
> feat: derive Copy trait for messages where possible

- prost-derive/src/lib.rs
- prost/src/encoding.rs
- prost/src/lib.rs
- prost/src/message.rs
- prost/src/types.rs
- tests/src/build.rs
- tests/src/lib.rs
- tests/src/no_shadowed_types.proto
- tests/src/no_shadowed_types.rs
> Change generated functions signatures to remove type parameters

- prost-build/src/code_generator.rs
- tests/src/derive_copy.rs
Due to two pull requests changing the same function a build error occurred. `fields` has move to inside `oneof` and has changed type.
> fix: Build error due to merge conflict

- .github/workflows/ci.yml
Instead of rebuilding everything with Rust 1.70 (MSRV), use `cargo hack` to only build published crates at their specified `rust-version`.
> chore: Add ci to check MSRV

- .github/workflows/ci.yml
Add a job that only finished if all tests pass. This will be configured as a required test to make sure all jobs pass on every commit.
> ci: Add all tests pass job

- prepare-release.sh
The release scripts were broken by moving `prost` crate into a separated directory in #1033.
Fixes #1054
> build: Fix release scripts

- protobuf/Cargo.toml
libz-sys is a optional dependency of a private crate that is never enabled.
> build(deps): Remove unused libz-sys

- .github/workflows/ci.yml
- README.md
- prepare-release.sh
- prost/README.md
- ci: Ensure both README are the same and prost version is correct
- docs: Update prost version in README
- build: Fix prepare-release.sh for README
Fixes #1053
> ci: Ensure both README are the same and prost version is correct 

- .github/workflows/ci.yml
- prost-build/src/code_generator/c_escaping.rs
- prost-build/src/collections.rs
- prost-build/src/config.rs
- prost-build/src/lib.rs
- prost/src/name.rs
- tests/src/lib.rs
also ci: Check for documentation warnings
> docs: Fix broken link warnings

- .github/workflows/ci.yml
Prevent CI breakage when new lints are added to stable rust version by explicitly choosing the rust version used for the clippy job.
> ci: Set rust version of clippy job to a fixed version

- prepare-release.sh
The prepare release script got out of sync with the actual code.
- Automatically update the minor version in the readme
- Cargo.toml version was moved in #1036
> build: Fix prepare-release.sh

- prost-derive/src/lib.rs
- tests/src/enum_keyword_variant.proto
The generated code uses `Self::Error` to refer to `::prost::UnknownEnumValue`, but the term `Error` is not unique when an enum variant is called `Error`. Use the full type name to resolve the ambiguity.
The compiler reported:
```
error: ambiguous associated item
--> /home/ircdev/src/prost/target/debug/build/tests-no-std-e27db7197924752f/out/enum_keyword_variant.rs:2:68
|
2   | #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
|                                                                    ^^^^^^^^^^^^^^^^^^^^
|
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #57644 <https://github.com/rust-lang/rust/issues/57644>
note: …
```
> fix: Enum variant named `Error` causes ambiguous item

- CHANGELOG.md
- Cargo.toml
- README.md
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- prost/Cargo.toml
- prost/README.md
- prost/src/lib.rs
* Enum variant named Error causes ambiguous item (#1098)
> chore: prepare 0.13.1 release

- .github/workflows/ci.yml
- prost-types/src/lib.rs
- prost/src/encoding.rs
- prost/src/lib.rs
Cargo clippy reports:
```
warning: usage of a legacy numeric method
--> prost/src/lib.rs:71:24
|
71 |     if length > usize::max_value() as u64 {
|                        ^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
help: use the associated constant instead
|
71 |     if length > usize::MAX as u64 {
|                        ~~~
```
> style: Remove use of legacy numeric constants

- prost-types/src/datetime.rs
Two bugs revealed so far from fuzz testing in `bilrost`:
* `parse_two_digit_numeric` does not check the length of its input before calling `split_at`, potentially causing a panic
* a logic error in the translation of `year_to_seconds` from the original musl implementation caused it to treat the year 1900 as a leap year, causing (i believe) every date from 1900-01-01 to 1900-03-01 to be offset one day into the past when converting from `DateTime` to `Timestamp`.
> fix(prost-types): Fix date-time parsing

- tests-2018/Cargo.toml
- tests-no-std/Cargo.toml
- tests/Cargo.toml
Only the crate `tests-2015` uses the feature `edition-2015`, but the code is shared with the `tests` crate.
Same for `tests-no-std` which disables feature `std`, but reuses the code with the `tests` crate.
Therefore the `tests`, `tests-2018` and `tests-no-std` crates should be configured to ignore the lint about missing features.
Cargo clippy reports:
```
warning: unexpected `cfg` condition value: `edition-2015`
--> tests-no-std/../tests/src/build.rs:5:14
|
5 |     if #[cfg(feature = "edition-2015")] {
|              ^^^^^^^-----------------
|              |
|              help: remove the condition
|
= note: no expected values for `feature`
= help: consider adding `edition-2015` as a feature in `Cargo.toml`
= note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.htm …
```
> build: Ignore missing features in `tests` crates

- prost-derive/Cargo.toml
The nightly compiler warns about a incompatibility of the Cargo.toml for the next edition. Use the backwards compatible `proc-macro` in the Cargo.toml.
Compiler reports:
```
warning: prost/prost-derive/Cargo.toml: `proc_macro` is deprecated in favor of `proc-macro` and will not work in the 2024 edition
```
> build: Use `proc-macro` in Cargo.toml

- prost-types/src/datetime.rs
`u8 as FromStr` tolerates a leading `+` character, so before this change for any 2-digit component of the path, "05" and "+5" are basically equivalent. we shouldn't tolerate this, it's weird.
> fix(prost-types): '+' is not a numeric digit

- protobuf/build.rs
Prevent placing build artifacts in the protobuf source tree by choosing a build directory in the out dir. A `cargo clean` will clean up the build artifacts.
> build: Use separated build directory for protobuf

- prost-types/src/datetime.rs
- prost-types/src/timestamp.rs
The converstion from the private type DateTime to public type Timestamp is fallible when the DateTime is invalid. All code paths that used `DateTime::into::<Timestamp>()` first check whether the DateTime is valid and then do the conversion, therefore this problem was not visible. https://github.com/tokio-rs/prost/issues/893 points out that some conversions panic, however all these DateTime are invalid.
Solution: Replace `impl From<DateTime> for Timestamp` with `TryFrom` and remove the manual `is_valid` checks before the conversion.
I added the test cases from the issue and roundtrip test between DateTime and Timestamp.
> fix(prost-types): Converting DateTime to Timestamp is fallible

- prost-types/src/datetime.rs
`chrono` is able to parse timestamps which are more precise then nanoseconds. We can also do that but truncating the digits.
> fix(prost-types): Parse timestamp with long second fraction

- Cargo.toml
- fuzz/Cargo.toml
The fuzzing targets need some love. I got them working again with these changes:
- build(fuzz): Add missing dependency
- build(fuzz): Use released version of `libfizzer-sys`
- build(fuzz): create `fuzz` is not part of workspace
- build(fuzz): afl is not in root directory
> build(fuzz): Fix building of fuzzing targets

- prost-types/src/duration.rs
Duration `-0.123s` was formatted as a positive number.
> fix(prost-types): Format negative fractional duration

- prost-derive/src/lib.rs
- prost/benches/varint.rs
- prost/src/encoding.rs
- prost/src/encoding/length_delimiter.rs
- prost/src/encoding/varint.rs
- prost/src/encoding/wire_type.rs
- prost/src/lib.rs
- prost/src/message.rs
- prost/src/types.rs
While the `encoding` module is undocumented and not stable, there are known users. Leave an alias in place to prevent breaking them.
> style: Move encoding functions into separate modules

- prost-types/src/datetime.rs
`chrono` allows a negative zero local offset. I think we should follow their example.
The RFC 3339 spec says this is a special value, but doesn't specify how to handle the situation. https://www.rfc-editor.org/rfc/rfc3339#section-4.3
> fix(prost-types): Allow unknown local time offset

- .github/workflows/ci.yml
Running `cargo test --all-targets` will not run doctests, as noted in the removed comments.
Another effect is that Cargo.toml instructions for not running a test are ignored. For example, benchmarks are tested, but no unit tests are inside and bins marked with `test = false` are run.
I diffed the text output of running `cargo test` and `cargo test --all-targets` and concluded that no useful test will be skipped when running just `cargo test`.
> ci: Run `cargo test` without `all-targets`

- Cargo.toml
- fuzz/Cargo.toml
- fuzz/fuzzers/proto2.rs
`cargo-fuzz` recommends adding the `fuzz` crate to the workspace. It seems the problem of not compiling is fixed with recent dependencies.
source: https://github.com/rust-fuzz/cargo-fuzz?tab=readme-ov-file#usage
> build(fuzz): Add fuzz targets to workspace

- protobuf/build.rs
The build script of crate `protobuf` installs some proto-files for testing in the prefix dir. However the only user is the same build script. Therefore we can skip the install and use the files directly.
Use `absolute` path instead of `canonical` path, as `protoc` on Windows is not able to process `canonical` paths. This is sort of documented in https://doc.rust-lang.org/std/fs/fn.canonicalize.html
> build(protobuf): Don't install unused test proto

- .github/workflows/ci.yml
- protobuf/build.rs
```
warning: the borrowed expression implements the required traits
--> protobuf/build.rs:143:14
|
143 | ...rg(&format!("-DCMAKE_INSTALL_PREFIX={}", prefix_dir.display(...
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `format!("-DCMAKE_INSTALL_PREFIX={}", prefix_dir.display())`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
= note: `#[warn(clippy::needless_borrows_for_generic_args)]` on by default
```
> style: Remove needless borrow

- fuzz/Cargo.toml
- fuzz/fuzzers/parse_date.rs
Add a fuzzing target for parsing into a Timestamp and comparing the result with crate chrono.
> tests(fuzz): Add `parse_date` fuzzing target

- .github/workflows/ci.yml
- tests/src/decode_error.rs
Remove feature check for a feature that doesn't exist in the `tests` crate. This allows clippy to be updated.
> ci(clippy): Update to cargo clippy version 1.80

- prost-build/README.md
- prost-build/src/config.rs
- prost-build/src/lib.rs
Set the path to `protoc` executable to be used by `prost-build`
Use the provided path to find `protoc`. This can either be a file name which is searched for in the `PATH` or an aboslute path to use a specific executable.
This API is needed during `prost` development to use the repo compiled `protoc` on the `.proto`-files in the same repo: https://github.com/caspermeijn/prost/commit/1e4f390d699cbd7b36fcdd3a53dc63a2e2debbc6
> feat(prost-build): Add protoc executable path to Config

- .github/workflows/ci.yml
- tests/src/lib.rs
The crate `tests-no-std` was never build without std in CI. Therefore the build was broken.
Use the `no_std` compatible `anyhow` calls and run `no-std-check` on the crate.
> tests: Fix build without std

- .github/workflows/ci.yml
- KANI.md
- prost-types/Cargo.toml
- prost-types/src/duration.rs
- prost-types/src/timestamp.rs
Three proptests are executed as kani proofs in CI. Make that explicit by marking them as kani proof.
This removes the dependency on propproof dependency when using kani.
> tests: Change some proptest to kani proofs

- fuzz/Cargo.toml
- fuzz/fuzzers/parse_duration.rs
Add a fuzzing target for parsing into a Duration.
> tests(fuzz): Add `parse_duration` fuzzing target

- Cargo.toml
Rust 1.71.1 was released on Aug. 3, 2023 (1 year ago at this time). This allows to bump `pulldown-cmark` dependency to the latest version.
> build: Increase MSRV to 1.71.1

- prost-build/src/lib.rs
- tests/src/bootstrap.rs
There are multiple implementations of assert on fixture files. Some also write to the file to ease development and some normalize line endings. Unify their implementation so that they work similar.
> chore: unify assert on fixtures

- protobuf/build.rs
Crate `protobuf` compiles some .proto-files from the checked out repo in `third_party/protobuf`. Those files can use newest features from `protoc`. Therefore during development the `protoc` in `PATH` must be the same version or newer than in `third_party/protobuf`.
The crate already builds a `protoc` compiler from the checked out repo to be used in conformance executable. Use that specific `protoc` for compiling the .proto-files in the crate.
This doesn't influence the `protoc` used in crate `tests` nor published crates.
> build(protobuf): Use same `protoc` from same repo as .proto-files

- prost-build/src/lib.rs
Update the example in the generated documenation.
- Use `cargo add` to dependencies, instead of refering to the latest version
- Add more protobuf comments, as the documenation is mentioned in the last step
> docs(prost-build): Use `cargo add` in example

- prost-build/src/config.rs
- prost-build/src/message_graph.rs
`MessageGraph` is an internal type. The currenly implementation can't fail, so it doesn't have to return a `Result`
> style: `MessageGraph::new()` can't actually fail

- prost-build/src/config.rs
- prost-build/src/extern_paths.rs
Trigger all errors of `prost-build` and check the produced error text
> tests(prost-build): Validate error texts

- prost-build/src/config.rs
Due to conflicting PR #1152 and #1150 tests were failing.
> tests(prost-build): Fix error texts

- prost-build/src/code_generator.rs
- prost-build/src/fixtures/helloworld/_expected_helloworld.rs
- prost-build/src/fixtures/helloworld/_expected_helloworld_formatted.rs
- prost-types/src/compiler.rs
- prost-types/src/protobuf.rs
Makes `as_str_name` generate `match self` using `Self::` where possible, consistent with `from_str_name`
> style(generated-code): use Self in as_str_name

- prost-types/src/datetime.rs
- prost-types/src/duration.rs
- prost-types/src/timestamp.rs
Make `normalize` easier to use, by introducing `Duration::normalized` and `Timestamp::normalized`. They do the same as there `normalize` equivalents, but return a copy for ease of use.
> feat(prost-types): Add `normalized` functions

- prost-build/src/config.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes.rs
- prost-build/src/fixtures/field_attributes/_expected_field_attributes_formatted.rs
- prost-build/src/message_graph.rs
- prost-build/src/path.rs
- tests/src/boxed_field.proto
- tests/src/build.rs
- tests/src/lib.rs
Fix one of the problems I found while rebasing #705: boxed fields are not `Copy`
> fix(prost-build): Remove `derived(Copy)` on boxed fields

- CHANGELOG.md
- Cargo.toml
- README.md
- prost-build/Cargo.toml
- prost-build/src/lib.rs
- prost-derive/src/lib.rs
- prost-types/Cargo.toml
- prost-types/src/lib.rs
- prost/Cargo.toml
- prost/README.md
- prost/src/lib.rs
Apparently, `prost-build::Config::boxed` has been broken since 0.13.0. With that fix (#1157)  in a new release would be nice.
> chore: Release version 0.13.3

- prost-build/src/code_generator.rs
- prost-build/src/path.rs
- prost-types/src/conversions.rs
- prost/src/encoding.rs
`cargo clippy` reports:
```
error: the following explicit lifetimes could be elided: 'a
--> prost-types/src/conversions.rs:46:6
|
46 | impl<'a> From<&'a str> for Value {
|      ^^        ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `-D clippy::needless-lifetimes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_lifetimes)]`
help: elide the lifetimes
|
46 - impl<'a> From<&'a str> for Value {
46 + impl From<&str> for Value {
```
> style: Remove explicit lifetimes

- tests/build.rs
- tests/src/custom_debug.rs
- tests/src/lib.rs
- Rename `skip_debug` into `custom_debug`
- Move related tests to the module
> test(custom_debug): Merge `skip_debug` into `custom_debug`

- prost-build/src/config.rs
Removes the unnecessary empty line after the document.
> chore(build): Remove unnecessary empty line after document

- tests/build.rs
- tests/src/disable_comments.proto
- tests/src/disable_comments.rs
- tests/src/lib.rs
This test uses a invalid doctest to confirm `disable_comments` works as expected. Rename the test to what is tested.
> test: Rename `invalid_doctest` to `disable_comments`

- tests/build.rs
- tests/src/custom_attributes.proto
- tests/src/custom_attributes.rs
- tests/src/lib.rs
- Use package name `custom_attributes` to ease finding related files
- Add oneof fields to make every `field_attribute` part of the test
> test(custom_attributes): Move module to separate file

- prost/src/encoding/varint.rs
Give the compiler all the leverage to optimize `encoded_len_varint`:
* Construct a `NonZeroU64` to count leading zeros, as that can be faster on many platforms;
* Use `ilog2` instead of a handwritten expression to compute the base 2 algorithm, as the core library developers and the compiler would probably be in the best position to fine-tune it for all supported platforms.
With the `varint` benchmarks, I see slight improvements (1-3%) or no reproducible performance changes on 11th gen Intel Core and Mac M3.
> Use `NonZeroU64` to optimize `encoded_len_varint`

- prost/src/encoding.rs
- prost/src/encoding/varint.rs
The constness is not really needed anywhere in prost crates, but it won't hurt either.
> Make `key_len` and `encoding_len_varint` const

- tests/build.rs
- tests/src/default_enum_value.rs
- tests/src/lib.rs
- Check default of `CMsgRemoteClientBroadcastHeader`
> test(default_enum_value): Move tests to separate module

- prost-build/src/config.rs
Fixes #1213
We already support passing ``disable_comments`` to disable comment processing during the code generation.
However, when we compile FileDescriptorSet, we always pass ``--include_source_info``. These might cause a problem, especially when the file is later included into the final binary using ``include_bytes!`` e.g. because of the following:
- The comments might contain sensitive private information (comments + file location) which we don't want to be visible in the binary (e.g. when  someone disassemble it).
- It increases the size of the binary
Therefore, adding the ``skip_source_info`` argument allowing to disable it.  Altnerative fix could be to add it ``protoc_args`` by default, but this is not backwards compatible, because ``protoc_args`` are currently additive only.
> Add a config option to avoid passing include_source_info

- prost-build/src/ast.rs
- prost-build/src/code_generator.rs
Fixes clippy lints like this:
```
warning: this `map_or` is redundant
--> prost-build/src/ast.rs:104:9
|
104 | /         chars
105 | |             .next()
106 | |             .map_or(false, |c| c != ' ' || chars.next() == Some(' '))
| |_____________________________________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
= note: `#[warn(clippy::unnecessary_map_or)]` on by default
```
> style: Replace unnecessary `map_or`

- tests/build.rs
- tests/src/lib.rs
- tests/src/nesting.rs
> test(nesting): Move tests to separate module

- tests/build.rs
- tests/src/lib.rs
- tests/src/recursive_oneof.rs
> test(recursive_oneof): Move tests to separate module

- tests/build.rs
- tests/src/groups.rs
- tests/src/lib.rs
> test(groups): Move tests to separate module

- prost-build/src/code_generator.rs
- prost-build/src/config.rs
- prost-build/src/context.rs
- prost-build/src/lib.rs
- prost-build/src/message_graph.rs
Refactoring improvements to prost-build:
* Move compilation-global context data and logic around it from `CodeGenerator` to a new `Context` struct.
* Lift similar logic into `Context` from `MessageGraph`, where it caused some data duplication.
* Resolve some awkwardness about the `Config` reference needing to be mutable for its user-provided service generator, by exposing both from `Context` in a more disciplined way.
This also fixes a bug in the logic that determines whether `Copy` can be derived on a message, where a `boxed` config rule matching a field that is part of a oneof would be disregarded.
> Clean up `CodeGenerator` by moving compilation-global data and logic to `Context`

- tests/build.rs
- tests/src/default_string_escape.rs
- tests/src/lib.rs
> test(default_string_escape): Move tests to separate module

- prost-build/src/code_generator.rs
- prost-build/src/context.rs
Use enum getter function to compare enum values instead of `i32` values.
> style(prost-build): Use enum getter

- prost-build/src/config.rs
Inform `cargo` about the files and env vars used by `prost-build`. Then `cargo` can better determine when to rebuild a project.
- Emit `rerun-if-changed` for each proto file specified
- Emit `rerun-if-changed` for each include directory specified
- Emit `rerun-if-changed` if `file_descriptor_set_path` is set
- Emit `rerun-if-env-changed` for `PROTOC` and `PROTOC_INCLUDE`
https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed
BREAKING CHANGE: Previously `cargo` assumed it had to rerun `build.rs` if any files in the project changed. `prost-build` will now emit `rerun` commands, which means only the explicitly marked files cause a rerun. If your `build.rs` is dependent on any other file paths than those given to `prost-build`, then your `build.rs` needs to emit `rerun` …
> feat(prost-build): emit `rerun` commands

- prost-build/src/config.rs
- tests/build.rs
- tests/src/type_names.proto
- tests/src/type_names.rs
Changes the `type_name_domain` config to behave closer to the way `extern_path` does.
This allows setting more than 1 path to domain mappings.
The original behavior of clearing previous mappings didn't make a lot of sense to me, but perhaps it was working as intended. If that's the case, then this would be a feature instead of a fix I guess.
BREAKING CHANGE: The configuration for domain names of messages is now cumulative. All calls to prost_build::Config::type_name_domain are now concatenated. The previous behavior was that only the arguments of the last call were used. If you do multiple calls to type_name_domain, you need to remove all but the last call to maintain the same behavior.
> fix(prost-build): Make `type_name_domain` cumulative

- prost/src/message.rs
- tests/src/generic_derive.rs
- tests/src/lib.rs
Relaxes `Message`'s `Debug` trait bound.
BREAKING CHANGE: `trait Debug` was a supertrait of `trait Message`. This is no longer required by `prost`. If your code relies on `trait Debug` being implemented for every `impl Message`, you must now explicitly state that you require both Debug and Message. For example: `where M: Debug + Message`
> feat: Relax Message Debug trait bound

- prost-build/src/context.rs
- tests/build.rs
- tests/src/boxed_field.proto
- tests/src/boxed_field.rs
Repeated fields are stored in a `Vec`, and therefore they are already heap allocated.
BREAKING CHANGE: A repeated field that is manually marked as boxed was typed as `Vec<Box<T>>`. Those fields are now simply typed as `Vec<T>` to prevent double indirection. The `boxed` configuration is effectively ignored for repeated fields.
> fix(prost-build): Prevent repeated fields to be boxed

- README.md
- prost-types/Cargo.toml
- prost/Cargo.toml
- prost/README.md
Removes the deprecated prost-derive feature.
BREAKING CHANGE: Feature flag `prost-derive` is renamed to `derive`. Please rename any usage of `prost-derive` feature in your `Cargo.toml`.
> feat: Remove prost-derive feature

- .github/workflows/ci.yml
- prost-build/src/code_generator.rs
Prevents clippy warnings like:
```
warning: called `Iterator::last` on a `DoubleEndedIterator`; this will needlessly iterate the entire iterator
--> prost-build/src/code_generator.rs:473:54
|
473 |                         .and_then(|ty| ty.split('.').last())
|                                                      ^^^^^^ help: try: `next_back()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
= note: `#[warn(clippy::double_ended_iterator_last)]` on by default
```
> style: Use DoubleEndedIterator::next_back

- prost-build/src/ident.rs
- prost-build/src/lib.rs
- tests/src/enum_keyword_variant.proto
- tests/src/enum_keyword_variant.rs
- tests/src/ident_conversion.proto
- tests/src/lib.rs
In rust edition 2024 `gen` is a keyword.
- Prefix protobuf field name `r#gen`
- Rename variable names in our code
> style: Prepare for 2024 keyword `gen`

- prost-build/src/message_graph.rs
- prost-derive/src/lib.rs
Ref: https://doc.rust-lang.org/edition-guide/rust-2024/match-ergonomics.html
The direct impact of this is, some prost structs are modded in our codebase by (1) use cargo-expand to unfold prost implementation (2) use script to replace certain types. After upgrading to edition-2024 the output from (1) triggers complaint from rust.
> harden `ref mut` according to edition 2024

- prost-build/src/lib.rs
> style: fix typo

- prost-types/README.md
Hi! I fixed a broken relative link to the project LICENSE file in `prost-types/README.md`. The previous link had incorrect path syntax.
> docs: update dead link LICENSE in `prost-types/README.md`

- .github/workflows/ci.yml
Temporary set workspace edition to 2024 to enable more lints in the macros. This verifies that the generated code in our macros is 2024 edition compatible.
> ci: Run clippy with edition 2024 enabled

- prost-build/src/config.rs
This reverts commit 7c16959496b99157e53d59323c7b46470c95137e.
In version 0.14.0, `prost-build` began emitting `rerun` commands. This change introduced regressions for some users—for example, those generating `protos` from an `includes` directory. These edge cases are non-trivial to address comprehensively, so version 0.14.1 reverts the emission of `rerun` commands. For more details, see issue #1296.
> Revert "feat(prost-build): emit `rerun` commands (#1140)"

- prost-build/src/code_generator.rs
- tests/build.rs
- tests/src/lib.rs
- tests/src/oneof_name_conflict.proto
- tests/src/oneof_name_conflict.rs
When a oneof field and a message have the same name, then `prost-build` will generate invalid code. The generated types have the same name. With this change the oneof enum is renamed to resolve the conflict. This is not a breaking change, because the old code didn't compile.
Example of generated code for `oneof_name_conflict.proto`:
```rust
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Bakery {
#[prost(oneof = "bakery::BreadOneOf", tags = "1, 2")]
pub bread: ::core::option::Option<bakery::BreadOneOf>,
}
/// Nested message and enum types in `Bakery`.
pub mod bakery {
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Bread {
#[prost(int32, tag = "3")]
pub weight: i32,
}
#[derive(Clone, PartialEq, Eq, …
```
> fix(prost-build): Resolve OneOf type name conflict with embedded message

- prost/src/encoding.rs
An additional test to force testing non-contiguous chunks in Buf. This is necessary, since this edge case is, theoretically, supported by the Buf trait.
> tests: add test for split buffer varint decoding

- tests/build.rs
Prevent memory allocation in PathBuf and cloning directly after it.
Prevents this clippy warning:
```
warning: this call to `clone` can be replaced with `std::slice::from_ref`
--> tests-2018/../tests/build.rs:21:20
|
21 |     let includes = &[src.clone()];
|                    ^^^^^^^^^^^^^^ help: try: `std::slice::from_ref(&src)`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#cloned_ref_to_slice_refs
= note: `#[warn(clippy::cloned_ref_to_slice_refs)]` on by default
```
> style: Remove allocation in tests

- tests/build.rs
- tests/src/lib.rs
- tests/src/result_enum.proto
- tests/src/result_enum.rs
- Create a explicit test in separate module
- Rename package to match the filename
> test(result_enum): Move test to separate module
