tokio-rs/prost

prost-derive/src/prost-derive.rs
src/encoding.rs

Grab bag of fixes and improvements.

Derive fixes

---

prost-build/src/message_graph.rs

Add comment explaining behavior of add_message in prost_build

---

prost-build/src/ident.rs

fix for https://github.com/danburkert/prost/issues/179

Fix for unsupported keyword raw identifiers

---

src/encoding.rs

A bunch of micro-optimisations for the decoding path. Despite the introduction of unsafe code, these are all safe.
r? @danburkert

Micro-optimise decoding

---

prost-derive/src/lib.rs
tests/src/message_encoding.rs

Fix derive macro tag inference

---

prost-derive/src/field/map.rs
prost-derive/src/field/scalar.rs

Extracted just the method getter/setter changes from #234, plus a few improvements.

Document generated methods

---

.travis.yml
Cargo.toml
benches/varint.rs
conformance/Cargo.toml
conformance/src/main.rs
prost-build/Cargo.toml
prost-build/src/lib.rs
prost-derive/src/field/map.rs
prost-types/Cargo.toml
protobuf/Cargo.toml
protobuf/benches/dataset.rs
src/encoding.rs
src/lib.rs
src/message.rs
src/types.rs
tests-2015/Cargo.toml
tests/Cargo.toml
tests/src/lib.rs

This is #246, rebased over current master and with a commit containing some additional fixups.  I didn't want to clobber @LucioFranco's branch so it's in a separate PR.

Update bytes 0.5

---

prost-derive/src/lib.rs
src/lib.rs

Update derive to not require bytes

---

README.md

Remove bytes depdency requirement from the readme

---

README.md
conformance/Cargo.toml
prost-build/Cargo.toml

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Update outdated dependencies

---

.github/workflows/continuous-integration-workflow.yaml
src/encoding.rs

This is #314, but disables for all workflows.  I'm interested in getting some timing information; if this doesn't have much of an impact on CI times then I'm happy to merge, otherwise it'd be good to dig deeper into why the caching failures are occurring.

CI: disable Cargo target directory caching

---

prost-build/Cargo.toml
prost-derive/Cargo.toml

This is the one dependency in my tree that causes a duplicate, please @danburkert I would be grateful if you merge this.

Update itertools 0.8 -> 0.9

---

prost-types/src/lib.rs

The protobuf spec for `Timestamp` states that:
negative second values with fractions must still have
non-negative nanos values that count forward in time
... but in v0.6.1 and earlier of `prost_types`, this is handled wrongly when converting to `SystemTime`, with the `nanos` value contributing to the `Duration` that is to be _subtracted_ from the `UNIX_EPOCH`:
https://github.com/danburkert/prost/blob/v0.6.1/prost-types/src/lib.rs#L142-L145
```Rust
let mut duration = Duration {
seconds: -timestamp.seconds,
nanos: timestamp.nanos,
};
```
So, for example `Timestamp { seconds: -20, nanos: 999_999_999 }` would result in a `Duration { seconds: 20, nanos: 999_999_999 }` to subtract from `UNIX_EPOCH`, instead of the correct value of 19 seconds + 1 nano before `UNIX_EPOCH`.
The bug was fixed in …

Validate Timestamp conversion from SystemTimes before UTC Epoch time

---

prost-build/src/code_generator.rs
prost-build/src/lib.rs
prost-derive/src/field/scalar.rs
prost-types/src/protobuf.rs
src/encoding.rs
src/types.rs
tests/src/message_encoding.rs

I made a hash of #337; this is that PR with a few extra commits of my own.

Optional support for bytes::Bytes type backing bytes field

---

Cargo.toml
src/encoding.rs

Convert existing quickcheck tests to proptest.

quickcheck -> proptest

---

prost-build/build.rs
prost-build/src/lib.rs

improve compatibility with alpine build hosts

---

prost-build/Cargo.toml
prost-derive/Cargo.toml

Tests all pass locally for me; let me know if there is anything else I can help do to test.

build(deps): update to itertools 0.10

---

prost-build/src/lib.rs

This is a reopening of #441 since there seems to be a bug with the PR.

chore(build): Fix indentation of docs 

---

prost-build/build.rs

* Add pre-compiled protoc binary for ARM
* Enable build support for native binary.

Add support for Apple Silicon

---

prost-build/Cargo.toml

Updated petgraph to 0.6.

---

prost-build/src/lib.rs

Fix doc comment for field_attribute

---

prost-build/src/code_generator.rs

Doesn't make much difference since we're panicking either way, but at least we get a nicer error message

Fix out-of-bounds array index

---

prost-build/src/lib.rs

build: Skip empty protobuf files

---

Cargo.toml
prost-build/Cargo.toml
prost-build/src/lib.rs
prost-derive/Cargo.toml
prost-derive/src/lib.rs
prost-types/Cargo.toml
prost-types/src/lib.rs
src/lib.rs

Prepare `0.10.1` release

---

.github/workflows/continuous-integration-workflow.yaml
prost-derive/Cargo.toml
protobuf/Cargo.toml
tests-2015/Cargo.toml
tests-no-std/Cargo.toml
tests/Cargo.toml

Ensure things build when resolving dependencies to minimal versions.
Add a CI check as well.

Min-versions fixes and CI

---

prost-build/src/lib.rs

This commit adds two new compile functions that allow passing a `FileDescriptorSet` and it will generate the Rust code. This allows users to use libraries like `protox` directly and in an ergonomic way.
cc @andrewhickman

feat(build): Add direct fds compile support

---

Cargo.toml
protobuf/Cargo.toml

chore: Update to criterion 0.4

---

.github/workflows/continuous-integration-workflow.yaml

Updates to baptiste0928/cargo-install@v2.

chore: Update to baptiste0928/cargo-install@v2

---

prost-derive/src/lib.rs

Saw this typo and it was bothering me, so thought I'd just open a pull request!

Fix typo in bail message

---

.github/workflows/continuous-integration-workflow.yaml

Upgrading Kani and enabling a harness that was previously blocked by a Kani-side issue.

Enable 1 more Kani harness.

---

.github/workflows/continuous-integration-workflow.yaml
prost-derive/Cargo.toml
prost-derive/src/field/map.rs
prost-derive/src/field/mod.rs
prost-derive/src/field/oneof.rs
prost-derive/src/field/scalar.rs

(note this happens to include #867 too)

Update prost-derive to syn 2

---

prost-build/src/fixtures/alphabet/a.proto
prost-build/src/fixtures/alphabet/b.proto
prost-build/src/fixtures/alphabet/c.proto
prost-build/src/fixtures/alphabet/d.proto
prost-build/src/fixtures/alphabet/e.proto
prost-build/src/fixtures/alphabet/f.proto
prost-types/src/datetime.rs
tests/src/lib.rs

Corrects some typos in the repository.

Correct some typos

---

prost-build/Cargo.toml
prost-derive/Cargo.toml

Depend on itertools >=0.10, <0.12

build(deps): update to itertools 0.11

---

Cargo.toml
conformance/Cargo.toml
prost-build/Cargo.toml
tests-2015/Cargo.toml
tests-no-std/Cargo.toml
tests/Cargo.toml

chore: Update to env_logger 0.10

---

prost-build/Cargo.toml
prost-derive/Cargo.toml
prost-types/Cargo.toml

Each published crate should have a unique description.

chore: Update crate descriptions

---

prost-build/src/lib.rs

Many tests from `prost-build` wrote to the same temporary directory. Therefore these tests overwrite each other files. Because `cargo test` runs multi threaded some tests failed sometimes.

tests: Create a separate tempdir for each test

---

.github/dependabot.yml

Automatically create PRs to update the version number of Github Actions

ci(dependabot): Add github actions

---

prost/src/types.rs

feat: impl Name for Protobuf well-known wrapper types

---

prost-types/README.md

This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected "projet" to "project".
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

.github/workflows/ci.yml
README.md

Add CI job to make sure it stays up to date

docs: Update the readme MSRV to the actual number
